appnotasescola/appnotasescola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls', namespace="principal")),
    path('accounts/', include("allauth.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
    
]

appnotasescola/principal/urls.py
from django.urls import path  

from . import views

app_name = "principal"

urlpatterns = [ 
        path('', views.HomePageView.as_view(), name='home'),
        path('', views.HomePageView.as_view(), name='comunicados'),
        
              
]

appnotasescola/principal/models.py
from django.db import models

# Create your models here.

appnotasescola/principal/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "home.html"
    
    
    

    
  


    
    


    

appnotasescola/appnotasescola/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'principal:home' %}">App Notas</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'principal:comunicados' %}">Comunicados</a>
                    </li>                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

    

appnotasescola/principal/templates/comunicados.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
 
    

{% endblock %}

{% block title %} Comunicados aos professores {% endblock %}

{% block content %} 
     <h1>O nosso objetivo é ser uma ferramenta muito útil aos professores!</h1>

     <p>Uma aplicação que verifica as notas dos alunos e responde com sua média para avaliação</p> 


       
     <img src= {% static 'images/N.png' %} />
     {% endblock %}

appnotasescola/principal/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
 
    Página Inicial

{% endblock %}

{% block title %} App Notas {% endblock %}

{% block content %} 
    {% if user.is_authenticated %}
    Olá {{ user.username }}
    !
    <p>Sim você está logado</p>

<h1>Média de Alunos</h1>
    
<table class="table table-dark">
  <thead>
    <tr>
      <th>Cód do Aluno</th>
      <th>Nome Aluno</th>
      <th>Nota CAEd</th>
      <th>Nota SED</th>
      <th>Média</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="digite código" required>
        </div></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="Campo Nome" required>
        </div></td>
      <td><p><a href="https://avaliacaoemonitoramentosaopaulo.caeddigital.net/#!/minhapagina">nota</a></p></td>
      <td><a href="https://sed.educacao.sp.gov.br">nota</a></p></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="valor da media*" required>
        </div></td>
    </tr>
    <tr>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="digite código" required>
        </div></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="Campo Nome" required>
        </div></td>
      <td><p><a href="https://avaliacaoemonitoramentosaopaulo.caeddigital.net/#!/minhapagina">nota</a></p></td>
      <td><a href="https://sed.educacao.sp.gov.br">nota</a></p></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="valor da media*" required>
        </div></td>
    </tr>
    <tr>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="digite código" required>
        </div></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="Campo Nome" required>
        </div></td>
      <td><p><a href="https://avaliacaoemonitoramentosaopaulo.caeddigital.net/#!/minhapagina">nota</a></p></td>
      <td><a href="https://sed.educacao.sp.gov.br">nota</a></p></td>
      <td><div class="field">
            <label for="media"></label>
            <input type="text" id="nome" name="nome" placeholder="valor da media*" required>
        </div></td>
    </tr>
  </tbody>
</table>







<style>
footer {
  text-align:center;
  padding: 3px;
  background-color: Darkgray;
  color: gray;
}
</style>
</head>
<body>

<footer>
  <p>
  <a href="https://avaliacaoemonitoramentosaopaulo.caeddigital.net/#!/pagina-inicial"><button style="background: #069cc2; border-radius: 6px; padding: 15px; cursor: pointer; color: #fff; border: none; font-size: 16px;">CAEd</button></a>
  <a href="https://sed.educacao.sp.gov.br/"><button style="background: #069cc2; border-radius: 6px; padding: 15px; cursor: pointer; color: #fff; border: none; font-size: 16px;">SED</button></a></p>
</footer>

    {% else %}
    

     <h1>Bem vindo!</h1>

     <p>Este é o protótipo de um aplicativo desenvolvido pelos alunos do curso de Tecnologia da Informação da Univesp.</p> 

     <p>Aqui, você professor, tem uma ferramenta Web para auxiliar na avaliação de desempenho
     dos estudantes. Acessando as plataformas da Secretaria do Estado de São Paulo:
     O SED ( Secretaria Escolar Digital ) e o CAEd para coleta de notas e cálculo de média. </p>

     <p>Crie o seu login em cadastro e acesse.</p>
    

     <img src= {% static 'images/N.png' %} />
     {% endif %}
     {% endblock %}